spring:
  application:
    name: zipkin
    zipkin:
      enabled: true
      base-url: http://localhost:9411
    sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1
        percentage: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/