spring:
  application:
    name: serverA
    zipkin:
      enabled: true
      base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1
        percentage: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 3300

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  server:
    port: 3000

#security:
#  basic:
#    enabled: false
#
#management:
#  security:
#    enabled: false